language: python
install: "pip install -r requirements.txt"

script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings (will fix later)
  # - ANSIBLE0011: Disabled for all tasks which should be named
  - find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011  {} +
