---
- hosts: buildservers
  user: vagrant
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - oracle-java
    - jenkins

  environment: "{{proxy_env}}"   # Make sure to set/unset proxy in vars/default.yml
