---
- hosts: micro_appservers
  user: vagrant
  sudo: yes

  vars_files:
     - vars/default.yml

  roles:
    - hosts
    - common
    - oracle-java
    - nginx
    - rstats
    - logstash
    - microservice-appserver

  environment: "{{proxy_env}}"   # Make sure to set/unset proxy in vars/default.yml
