---
- name: Add dojo user account
  user:
    name: dojo
    comment: "Dojo jumpstation account"

- name: install xfce
  apt: pkg={{item}} state=present force=yes
  with_items:
    - xfce4
    - firefox
    - chromium-browser
    - vnc4server
    - imagemagick
    - imagemagick-doc

- name: install vnc configuration
  sudo: yes
  sudo_user: dojo
  copy: src=.Xauthority dest=/home/dojo/.Xauthority force=yes mode=700 owner=dojo

- sudo: yes
  sudo_user: dojo
  command: mkdir /home/dojo/.vnc/
  ignore_errors: yes

- name: install vnc configuration
  copy: src={{item}} dest=/home/dojo/.vnc/{{item}} force=yes mode=700 owner=dojo
  with_items:
      - passwd
      - xstartup

- name: install vnc init script
  copy: src=vncserver dest=/etc/init.d/vncserver mode=0755 owner=root

- name: register vncserver as service
  raw: sudo update-rc.d vncserver defaults
